#!/bin/bash

set -e

## Ask for admin password upfront
sudo -v

## Update, upgrade
sudo apt-get update
sudo apt-get -y dist-upgrade

sudo apt-get install \
    curl \
    wget \
    rsync \
    git \
    mercurial \
    bash-completion \
    imagemagick \
    exuberant-ctags \
    python-pygments

sudo apt-get install \
    tmux \
    vim-nox \
    keepassx \
    iceweasel \
    gpick \
    fontforge \
    trimage \
    scribus 

## Fonts
sudo apt-get install \
    fonts-inconsolata \
    fonts-droid

## Final upgrade and clean up
sudo apt-get upgrade
sudo apt-get autoremove
sudo apt-get clean
