#!/bin/bash


npm install -g \
    david \
    bower \
    component \
    gulp \
    jade \
    uglify-js \
    csso \
    html-minifier \
    js-beautify \
    stylestats \
    colorguard \
    complexity-report \
    plato \
    license-gen \
    harp
