# ~/.tmux.conf
#
# Tmux configuration
# ref: https://tmux.github.io/

# ======================================= #
#   Base Configuration
# ======================================= #

# History settings
set-option -g history-limit 10000

# Start numbering at 1
set -g base-index 1
setw -g pane-base-index 1

# No delay for escape key
set -sg escape-time 0

# Vi-style mode keys
setw -g mode-keys vi

# Allow the arrow key to be used immediately after changing windows
set-option -g repeat-time 0

# Enable true color support
# For Alacritty, set: TERM = "xterm-256color"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Enable automatic renaming to directory basename
set -g automatic-rename on
set -g automatic-rename-format "#{b:pane_current_path}"

# Enable activity alerts
setw -g monitor-activity on
set -g visual-activity on

# Enable mouse mode (tmux 2.1 and above)
set -g mouse on

# ======================================= #
#   Key Bindings
# ======================================= #

# Remap <tmux-prefix> to Ctrl + a
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Move window (tab)
# <tmux-prefix> Shift + Left
bind-key S-Left swap-window -t -1
# <tmux-prefix> Shift + Right
bind-key S-Right swap-window -t +1

# Split window vertically and horizontally on the current directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
# Create a new window on the current directory
bind c new-window -c "#{pane_current_path}"

# Use system clipboard in vi-copy mode
# Arch: sudo pacman -S wl-clipboard
if-shell 'grep -qi "Arch" /etc/os-release' \
    'bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy --foreground"'
# Debian: sudo apt install xclip
if-shell 'grep -qi "Debian" /etc/os-release' \
    'bind-key -T copy-mode-vi y copy-pipe "xclip -selection clipboard"'

# Reload source file
bind-key r source-file ~/.tmux.conf \; display-message "Configuration reloaded"

# ======================================= #
#   TPM and Themes, Plugins
# ======================================= #

# Enable TPM
set -g @plugin '~/.tmux/plugins/tpm'

# Theme Catppuccin et settings
source-file ~/.tmux/catppuccin.theme.conf

# Other plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Initialize TPM (must be at the bottom of .tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
