language: bash

os: linux
dist: stretch
sudo: required

install:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - sudo apt install shellcheck vim-nox tmux

before_script:
  - bash --version
  - shellcheck --version
  - vim --version
  - tmux -V

script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc
  - shellcheck .bashrc .bash_profile bash/* bin/{license,unpack} bootstrap.sh

notifications:
  email: false
  irc: false
