language: generic

sudo: required

matrix:
  include:
    - os: linux
      dist: jessie
    - os: osx
      osx_image: xcode8

before_install:
  - ./test/env-travis.sh

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - git clone https://bymathias@github.com/bymathias/dotfiles.git ~/.dotfiles
  - cd .dotfiles
  - ./bootstrap.sh install

notifications:
  email: true
  irc: false
