language: generic

sudo: required

matrix:
  include:
    - os: linux
      dist: jessie
    - os: osx
      osx_image: xcode8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - ./bootstrap.sh install

notifications:
  email: true
  irc: false
