language: sh

sudo: false

os:
  - osx

osx_image: xcode8

before_install:
  - brew update
  - brew outdated shellcheck || brew upgrade shellcheck

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - ./bootstrap.sh install
