language: bash

os:
  - linux
  # - osx

matrix:
  include:
    - env: ENV=debian
      os: linux
      dist: stretch
      sudo: required
    # - env: ENV=macos
    #   os: osx
    #   osx_image: xcode8

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global github.user "travis"

install:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install shellcheck; fi
  # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi

before_script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc
  - shellcheck *.sh .bash* bash/*.bash init/*

script:
  - ./bootstrap.sh install

notifications:
  email: false
  irc: false
