language: generic

sudo: required

matrix:
  include:
    - env: ENV=debian
      os: linux
      dist: jessie
      addons:
        apt: { sources: [debian-sid], packages: [shellcheck] }
    - env: ENV=macos
      os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc

notifications:
  email: true
  irc: false
