language: bash

os:
  - linux

matrix:
  include:
    - env: ENV=debian
      os: linux
      dist: stretch
      sudo: required

before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global github.user "travis"

install:
  - git clone https://github.com/syngan/vim-vimlint /tmp/vim-vimlint
  - git clone https://github.com/ynkdir/vim-vimlparser /tmp/vim-vimlparser

before_script:
  - sh /tmp/vim-vimlint/bin/vimlint.sh -l /tmp/vim-vimlint -p /tmp/vim-vimlparser -v .vimrc
  - shellcheck bashrc bash_profile bash/* bin/{license,unpack} bootstrap.sh

script:
  - ./bootstrap.sh install

notifications:
  email: false
  irc: false
