sudo: required

language: sh

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - vim
      - shellcheck

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - ./bootstrap.sh install
