language: sh
sudo: required
os:
  - linux

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - ./bootstrap.sh install
