language: generic

sudo: required

matrix:
  include:
    - os: linux
      dist: jessie
    - os: osx
      osx_image: xcode8

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -O http://ftp.us.debian.org/debian/pool/main/v/vim/vim-nox_7.4.488-7_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then dpkg -i vim-nox_7.4.488-7_amd64.deb; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shellcheck; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install vim --with-override-system-vi; fi

before_script:
  - shellcheck bootstrap.sh .bashrc .bash_profile bash/*

script:
  - ./bootstrap.sh install
  - vim +PlugInstall +qall

notifications:
  email: true
  irc: false
