# Add Catppuccin theme plugin
set -g @plugin 'catppuccin/tmux'

# Set the Catppuccin flavor (e.g., mocha, macchiato, frappe, latte)
set -g @catppuccin_flavour 'mocha'

# Remove space between window titles
set -g window-status-separator ""

# Customize window title
set -g @catppuccin_window_default_text " #W"
set -g @catppuccin_window_text " #W"
set -g @catppuccin_window_current_text " #W"

# Left/right side of status bar
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=#{@thm_crust},bg=#{@thm_teal}] ❐ #[default]#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] #h:$USER #[default]"
set -g status-right '#[fg=#{@thm_crust},bg=#{@thm_teal}] session: #S '
