#!/bin/bash
# shellcheck disable=SC2034


## Regular
Red="\[\e[0;31m\]"
Green="\[\e[0;32m\]"
Yellow="\[\e[0;33m\]"
Blue="\[\e[0;34m\]"
Purple="\[\e[0;35m\]"
Cyan="\[\e[0;36m\]"
White="\[\e[0;37m\]"

## Bold
BRed="\[\e[1;31m\]"
BGreen="\[\e[1;32m\]"
BYellow="\[\e[1;33m\]"
BBlue="\[\e[1;34m\]"
BPurple="\[\e[1;35m\]"
BCyan="\[\e[1;36m\]"
BWhite="\[\e[1;37m\]"

## Underlined
URed="\[\e[4;31m\]"
UGreen="\[\e[4;32m\]"
UYellow="\[\e[4;33m\]"
UBlue="\[\e[4;34m\]"
UPurple="\[\e[4;35m\]"
UCyan="\[\e[4;36m\]"
UWhite="\[\e[4;37m\]"

## Background
BKRed="\[\e[41m\]"
BKGreen="\[\e[42m\]"
BKYellow="\[\e[43m\]"
BKBlue="\[\e[44m\]"
BKPurple="\[\e[45m\]"
BKCyan="\[\e[46m\]"
BKWhite="\[\e[47m\]"

## No Colors
NC="\[\e[0m\]"
