#!/bin/bash

export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:$PATH

## Custom bin scripts
[[ -d $HOME/.dotfiles/bin ]] && export PATH=$PATH:$HOME/.dotfiles/bin

## Node.js
[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh

## Nginx
[[ -d /opt/nginx/sbin ]] && export PATH="$PATH:/opt/nginx/sbin"

## Php
if [[ "$SYSTEM" == "Darwin" ]] && [[ -d "$(brew --prefix homebrew/php/php56)/bin" ]]; then
  PATH="$(brew --prefix homebrew/php/php56)/bin:$PATH"
fi

## RVM
## Add RVM to PATH for scripting
[[ -d $HOME/.rvm/bin ]] && export PATH="$PATH:$HOME/.rvm/bin"
## Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
