#!/bin/bash

export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## Custom bin scripts
[[ -d $HOME/.dotfiles/bin ]] && export PATH=$PATH:$HOME/.dotfiles/bin

## RVM
## Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
## Add RVM to PATH for scripting
[[ -d $HOME/.rvm/bin ]] && export PATH="$PATH:$HOME/.rvm/bin" 

## Node.js
[[ -s $HOME/.nvm/nvm.sh ]] && source $HOME/.nvm/nvm.sh

## Nginx
[[ -d /opt/nginx/sbin ]] && export PATH=$PATH:/opt/nginx/sbin

## Php
if [[ "$SYSTEM" == "Darwin" ]] && [[ -d "$(brew --prefix homebrew/php/php55)/bin" ]]; then
    PATH="$(brew --prefix homebrew/php/php55)/bin:$PATH"
fi
